name: snapchat_clone
flutter:
  uses-material-design: true

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.5+9
  image_picker: ^1.1.2
  path_provider: ^2.1.3
  shared_preferences: ^2.2.3
  flutter_staggered_grid_view: ^0.7.0

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0